### ISSUE TITLE
Use Viridis as color palette

### ISSUE THREAD

**Issue by Eisit** [daenuprobst/dashcoch#5]
Viridis or its siblings "Magma" or "Plasma" may be better colour palettes to represent numbers or densities on the map. Also designed for color-blindness.

See https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html for a quick overview.

**Comment by daenuprobst** [comment]
Ciao @Eisit, I actually used viridis in the beginning but then switched to a colormap that makes the visualisation less busy and easier to interpret (gradient between two colors). I also checked the current map against a range of colour vision deficiencies. Thanks for your input.
